osrf/vrx-docker

- vorc_server/vorc-server/Dockerfile
Updating Dockerfile to clone from `master` branches after osrf/vrx#228 and osrf/vorc#30 were merged into respective `master` branches.
I merged those two PRs before #19, so that I could update #19 before merging. But of course I forgot.
> Update github branches in Dockerfile

- run_trial.bash
- task_config/gymkhana.yaml
- vorc_server/vorc-server/Dockerfile
Adding task_config YAML file for the gymkhana task. Addresses #20 bullet 1.
Creating the PR for visibility so that @crvogt has a base YAML for creating configs for trials > 0.
~~Draft for now, because for some reason the boat cannot be moved. There's probably a bug either in my new gymkhana xacro or in the YAML. Oddly, when I launch the generated .world file, the topic is correct and the boat moves normally.~~ Fixed. Depends on osrf/vorc#31.
To test:
Add the feature branch in osrf/vorc#31 to the `git clone` line in `vorc_server/vorc-server/Dockerfile`:
```diff
- && git clone https://github.com/osrf/vorc.git
+ && git clone -b gymkhana_fix_for_evaluation https://github.com/osrf/vorc.git
```
In `vorc_server/vorc-server/run_vorc_trial.sh`, set `gui:=true` in the `roslaunch vorc_gazebo …
> Add gymkhana task_config

- team_config/shipghost/dockerhub_image.txt
Add `shipghost` solution discussed in #19 thanks to @crvogt, so that VORC has more than one team to test the multiscripts.
(Re)move the `generated/` directory, to start from scratch (so that the team score script doesn’t find extra tasks from previous runs and think a task score is missing):
```
mv generated generated_bak
```
This should prep both `ghostship` and `shipghost` teams:
```
./multi_scripts/prepare_all_teams.bash
```
Prepare just one task so the runs don’t take forever. I picked perception, the quickest to run.
Optionally, you could pick a slower task and manually change the `<running_state_duration>` to a shorter duration (default 300 seconds) in  `generated/task_generated/*/worlds/*.world` files.
```
./prepare_task_trials.bash perception
```
This should run both teams on all …
> Add shipghost team solution

- run_trial.bash
Removes `VRX_EXIT_ON_COMPLETION` environment variable from `run_trial.bash`, so that the new SDF shutdown flag added in https://github.com/osrf/vorc/pull/35 are respected.
(This change is needed because currently, the environment variable overwrites SDF parameters, by design. See https://github.com/osrf/vorc/pull/35.)
What I have tested using the 2 branches in the pending PR above:
- Gymkhana, to make sure container doesn't shut down after the gates
- Stationkeeping, wayfinding, and perception, to make sure the container still shuts down
> Remove VRX_EXIT_ON_COMPLETION flag from VORC

- README.md
- generate_trial_video.bash
- replay_trial.bash
- run_trial.bash
- vorc_server/build_image.bash
- vorc_server/vorc-server/Dockerfile
- vorc_server/vorc-server/gz_utils.sh
- vorc_server/vorc-server/play_vorc_log.sh
- vorc_server/vorc-server/run_vorc_trial.sh
Addresses Infrastructure bullet 1 in https://github.com/osrf/vrx-docker/issues/20.
I completely rewrote the script for trial playback and video recording, so that the trial recording `state.log` is now played back from within the server Docker container, instead of on the host machine.
This was necessary, because during evaluation rehearsal, we found that when the log was being played back on the host machine, we had to do a hack of replicating the Docker container's `/vorc_ws/install/cora_description` directory structure on the host machine, in order for the robot to show up in Gazebo. Other environment configurations were probably also different between host and the server container depending on the evaluator.
Both the playback and video recording work quite well for me now. There were …
> Play back trial from within Docker container instead of host machine

- vorc_server/vorc-server/Dockerfile
We need to install the ROS compressed-image-transport package in the Docker server, otherwise the `compressed` image topics will not be available. See discussion in https://github.com/osrf/vorc-events/pull/21 .
> Adding compressed image topics

- prepare_task_trials.bash
- run_trial.bash
- task_config/gymkhana.yaml
- task_config/wayfinding.yaml
- vorc_server/vorc-server/run_vorc_trial.sh
Depends on https://github.com/osrf/vrx/pull/234 and https://github.com/osrf/vorc/pull/39
The script now launches the task-specific launch file, as opposed to everything using `marina.launch`. This is to make sure we're using the latest changes in the osrf/vorc repo for each task, as opposed to coupling `marina.launch` or even a new competition-specific launch file to vrx-docker and parsing competition-specific args.
Hopefully this means vrx-docker behavior is one step closer to regular vorc repo behavior with changes in the future.
This part of the PR will probably need backporting to vrx in `master` branch.
To test gymkhana acoustic pinger:
Change this line in `vorc_server/vorc-server/Dockerfile` to clone the new feature branch:
```
&& git clone -b fix_gymkhana_eval_pinger …
```
> Generate acoustic pinger YAML for gymkhana

- run_trial.bash
Draft until I can run a solution that uses CUDA.
Add `--runtime=nvidia` and `--privileged` for the *competitor* container.
We already had these two flags for the server container, but not the competitor container.
If the competitor uses NVIDIA CUDA-capable GPU, then the nvidia runtime flag is required.
Without `--runtime=nvidia`:
```
$ docker exec -it vorc-competitor-system bash
$ nvidia-smi
bash: nvidia-smi: command not found
```
With `--runtime=nvidia`, note I get the `CUDA Version: 11.0` line inside the Docker container:
```
$ docker exec -it vorc-competitor-system bash
$ nvidia-smi
Thu Dec 17 01:48:45 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.0     | …
```
> Enable NVIDIA runtime for competitor container

- README.md
- generate_trial_video.bash
- replay_trial.bash
- run_trial.bash
- vrx_server/vrx-server/Dockerfile
- vrx_server/vrx-server/gz_utils.sh
- vrx_server/vrx-server/play_vrx_log.sh
- vrx_server/vrx-server/run_vrx_trial.sh
- Backport #26 from VORC to VRX
- Backport #28 and #30 from VORC to VRX (very small fixes)
- Backport `robot_locked:=true` in launch command from VORC to VRX. Needed to eliminate errors like:
```
[Err] [scoring_plugin.cc:235] Unable to release [wamv_external_pivot_joint]
[Err] [scoring_plugin.cc:235] Unable to release [wamv_external_riser]
```
Note for future: This is likely a patch, as only the stationkeeping task should really lock the vehicle. `scoring_plugin.cc` probably should be changed so that it does not attempt to release the locking joints, which are nonexistent for other tasks.
To test:
```
docker network rm vorc-network
./vrx_server/build_image.bash -n
./prepare_team_wamv.bash example_team
vim generated/task_generated/stationkeeping/worlds/stationkeeping0.world …
```
> Backport #26, #28, #30 from VORC to VRX

- task_config/scan_dock_deliver.yaml
* This PR adds a scan_dock_deliver.yaml file that generates three practice worlds similar to the 3 stored in the vrx repository under `vrx_gazebo/worlds/2022_practice`.
* It requires the new file `scan_dock_deliver.xacro` in the vrx repository, so this PR must be tested in conjunction with [PR 391](https://github.com/osrf/vrx/pull/391) of that repository.
These instructions assume you have a workspace at `~/vrx_ws` with both vrx and vrx-docker installed, and have checked out the `M1chaelM/scan_dock_deliver_xacro` branch in vrx.
* First, switch to the root of the `vrx-docker` repository.  
```
cd ~/vrx_ws/src/vrx-docker
```
* Set some variables for convenience:
```
TASK=scan_dock_deliver
TRIAL=0
```
* Generate the trial worlds for the task
```
./prepare_task_trials.bash $TASK
```
* Verify …
> New yaml for scan, dock, deliver

- task_config/gymkhana.yaml
- task_config/scan_dock_deliver.yaml
* This PR adds a gymkhana.yaml file that generates three practice worlds similar to the 3 stored in the vrx repository under `vrx_gazebo/worlds/2022_practice`.
* It requires the new file `gymkhana.xacro` in the vrx repository, so this PR must be tested in conjunction with [PR 392](https://github.com/osrf/vrx/pull/392) of that repository.
These instructions assume you have a workspace at `~/vrx_ws` with both vrx and vrx-docker installed, and have checked out the `M1chaelM/gymkhana_xacro` branch in vrx.
* First, switch to the root of the `vrx-docker` repository.  
```
cd ~/vrx_ws/src/vrx-docker
```
* Set some variables for convenience:
```
TASK=gymkhana
TRIAL=0
```
* Generate the trial worlds for the task
```
./prepare_task_trials.bash $TASK
```
* Verify that 3 worlds are generated without …
> New yaml for gymkhana task

- multi_scripts/run_one_team_all_tasks.bash
- multi_scripts/run_one_team_one_task.bash
- run_trial.bash
This patch makes two changes:
* Replace the call to `python <python_file>` with `python3 <python_file>`. We updated `run_trial.bash` but there were two other scripts that need to be updated.
* Do not set the the environment variable `VRX_EXIT_ON_COMPLETION` to `true` when running a trial. This is problematic in the gymkhana task. The gymkhana task loads two other scoring plugins as auxiliary plugins. The `navigation_scoring_plugin` is used to detect when the WAM-V crosses the navigation channel. The `stationkeeping_scoring_plugin` is used to compute the error between the WAM-V and the pinger position. These two plugins have the `<per_plugin_exit_on_completion>` SDF parameter set to `false`. This is to prevent that the simulation terminates when the navigation channel is crossed. However, …
> Phase2 updates

- mwes/2022/vrx_2022_simple/basic_node.py
- prepare_team_wamv.bash
- vrx_server/vrx-server/run_vrx_trial.sh
When launching a task, we were passing `robot_locked` instead of `wamv_locked`.
> Fix wamv_locked parameter name

- vrx_server/vrx-server/Dockerfile
Our Dockerfile for the vrx-server clones the vrx repository directly from github. This practice is somewhat error prone because the image will not detect updates to the repository. By default it will instead cache the version that was present whenever the first time it was run, which means it is easy to accidentally end up testing against old code.
This PR addresses this issue by explicitly setting the version of the vrx repository to 1.6.1, which is the version of VRX that the 2022 competition will be run against. In future competitions it will need to be updated manually (or we can think of a better way to do this).
To test:
1. Rebuild the vrx-server:
```
cd ~/vrx_ws/src/vrx-docker
vrx_server/build_image.bash -n
```
2. Verify that the new version of the code is there:
```
docker run -it …
```
> explicitly specify vrx 1.6.1

- prepare_team_wamv.bash
This pull request updates the `prepare_team_wamv.bash` script to be used with Gazebo.
How to test it?
* Install VRX
* Set the ROS_HOME environment variable
```
export ROS_HOME=~/.ros
```
* Remember to source all the VRX `setup.bash`. E.g.:
```
. /opt/ros/humble/setup.bash
. ~/garden_ws/install/setup.bash
. ~/vrx2023_ws/install/setup.bash
```
* Run the script:
```
./prepare_team_wamv.bash example_team
```
* Launch the simulation with the generated WAM-V (update the `urdf` parameter with the path to your vrx-docker project:
```
ros2 launch vrx_gz competition.launch.py world:=sydney_regatta urdf:=/home/caguero/workspace/vrx-docker/generated/team_generated/example_team/example_team.urdf
```
> [Garden] Update prepare_team_wamv.bash

- prepare_team_wamv.bash
We are stuck troubleshooting #55 because the docker image isn't working. Initially, a minor update to `prepare_team_wamv.bash` was included as part of that PR. However, this update does not depend on the Docker image, and is needed for our validation process to work, so I have split it into a separate PR.
To test, please follow the [validation tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-validation) using `TEAM=example_team`.
> updating prepare_team_wamv.bash to expect ros 2

- vrx_server/build_image.bash
- vrx_server/vrx-server/Dockerfile
This PR attempts to resolve portability issues that prevented merging of #55 by using rocker to create a local image customized for the user's configuration, then building the vrx-server on top of it.
* Make sure rocker is installed: https://github.com/osrf/rocker
* Follow the testing instructions from #55
> Switching to rocker for portability

- prepare_team_wamv.bash
- run_trial.bash
- vrx_server/build_image.bash
- vrx_server/run_container.bash
- vrx_server/vrx-server/Dockerfile
- vrx_server/vrx-server/vrx_entrypoint.sh
This update should make it possible to build the vrx-server image with the VRX 2.0.0 release. To test, build the image and make sure it can launch a task.
```
./vrx_server/build_image.bash
```
from the root of the repository and verify that it builds. Further work is needed before we can test that it is working correctly (for example, it would be helpful to build a new example image that uses VRX 2.0.0, and the instructions for running a trial need to be updated).
* Bring up the vrx-server container manually.
```
SERVER_IMG=vrx-server-jammy
./vrx_server/run_container.bash -n vrx-server-system $SERVER_IMG   "-it --entrypoint /bin/bash"
```
* Source the environment.
```
source /opt/ros/humble/setup.bash
cd vrx_ws
. install/setup.bash
```
* Launch a task:
```
ros2 launch vrx_gz …
```
> updated vrx-server to jammy/humble/garden

- replay_trial.bash
- run_trial.bash
- utils/get_trial_score.py
- vrx_server/build_image.bash
- vrx_server/run_container.bash
- vrx_server/vrx-server/Dockerfile
- vrx_server/vrx-server/gz_utils.sh
- vrx_server/vrx-server/run_vrx_trial.sh
This PR updates `run_trial.bash` and related helper scripts to get the VRX testing tutorial working again using @j-herman 's example competitor image to test.
To test, follow the updated [VRX testing tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-testing) but use `example_team` as your team name so the script will use our ghost ship image as the competitor system.
Everything should work except the replay script, which will be addressed in a separate PR. The current script includes a cheap workaround for osrf/vrx#680 (see below for details).
> Fix automatic evaluation with `run_trial.bash`

- vrx_server/build_image.bash
- vrx_server/vrx-server/Dockerfile
Now that the final competition code is released, this resolves issue #64 by modifying the Dockerfile so we are always building from this version of the code.
To test:
* Run through the [testing tutorial](https://github.com/osrf/vrx/wiki/vrx_2023-testing) and make sure it rebuilds the vrx-server image and still works.
Bonus: added some explanatory comments to `buid_image.bash` because we are doing something a little unusual there.
> adding tag to use v2.3.1 when building the vrx server
